## PIN root dir, use full paths. Also, won't work with ~ sign for HOME
PIN_ROOT ?= /path/to/pin-2.14-71313-gcc.4.4.7-linux

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include $(PIN_ROOT)/source/tools/SimpleExamples/makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
