power = {'BUSES': {'Area': 6.41499,
           'Bus/Area': 6.41499,
           'Bus/Gate Leakage': 0.0172096,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.17946,
           'Bus/Subthreshold Leakage with power gating': 0.0672975,
           'Gate Leakage': 0.0172096,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.17946,
           'Subthreshold Leakage with power gating': 0.0672975},
 'Core': [{'Area': 1091.95,
           'Execution Unit/Area': 1042.48,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.202689,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.304033,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 4.44523,
           'Execution Unit/Instruction Scheduler/Area': 1004.7,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00146235,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.72302,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.664381,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0195747,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0105847,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.04861,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 60.828,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.31154,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 123.522,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 6.37058,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 4.72247,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 2.69123,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 47149.1,
           'Execution Unit/Instruction Scheduler/ROB/Area': 943.546,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.73561,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 47023.9,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2050.05,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 43.9842,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 16.5222,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2057.09,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 48.7263,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 19.224,
           'Execution Unit/Integer ALUs/Area': 3.76696,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.212233,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.476031,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.51291,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 3.21776,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 1.20666,
           'Execution Unit/Peak Dynamic': 47151.0,
           'Execution Unit/Register Files/Area': 28.3565,
           'Execution Unit/Register Files/Floating Point RF/Area': 9.63068,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.00825445,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.109431,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.128663,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.0497709,
           'Execution Unit/Register Files/Gate Leakage': 0.026159,
           'Execution Unit/Register Files/Integer RF/Area': 18.7258,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0179046,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.890859,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.911121,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.273097,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.103541,
           'Execution Unit/Register Files/Peak Dynamic': 0.890859,
           'Execution Unit/Register Files/Runtime Dynamic': 1.02055,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.40176,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.153311,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.406717,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0530429,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.448474,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 9.35872,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.804209,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.301578,
           'Execution Unit/Runtime Dynamic': 2068.49,
           'Execution Unit/Subthreshold Leakage': 54.5044,
           'Execution Unit/Subthreshold Leakage with power gating': 21.3935,
           'Gate Leakage': 4.83071,
           'Instruction Fetch Unit/Area': 21.801,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00551795,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00551795,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00486444,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00191499,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00192821,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0178285,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0508223,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.116615,
           'Instruction Fetch Unit/Instruction Buffer/Area': 2.64509,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.0346434,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 497.007,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 13.2107,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.290984,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.110014,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.43323,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.405419,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 14.8639,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 10.9923,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.43827,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 517.186,
           'Instruction Fetch Unit/Runtime Dynamic': 14.123,
           'Instruction Fetch Unit/Subthreshold Leakage': 1.36057,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.569799,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0260165,
           'L2/Runtime Dynamic': 0.0141737,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 9.12227,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.70761,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.68791,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0581307,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.112279,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.112279,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 6.23364,
           'Load Store Unit/Runtime Dynamic': 2.35391,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.27686,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.553721,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.73014,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.335351,
           'Memory Management Unit/Area': 0.747159,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0982585,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0986425,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.0311279,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0664823,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 2.32484,
           'Memory Management Unit/Runtime Dynamic': 0.165125,
           'Memory Management Unit/Subthreshold Leakage': 0.21543,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0918905,
           'Peak Dynamic': 48022.4,
           'Renaming Unit/Area': 8.8702,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 22.0682,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 5.36853e-06,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 3.35933,
           'Renaming Unit/Free List/Gate Leakage': 0.000408457,
           'Renaming Unit/Free List/Peak Dynamic': 2.47681,
           'Renaming Unit/Free List/Runtime Dynamic': 0.197504,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0098295,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.0053977,
           'Renaming Unit/Gate Leakage': 0.0402884,
           'Renaming Unit/Int Front End RAT/Area': 4.98475,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.00867665,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 318.553,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 12.6394,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.136044,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.0775451,
           'Renaming Unit/Peak Dynamic': 345.614,
           'Renaming Unit/Runtime Dynamic': 12.8369,
           'Renaming Unit/Subthreshold Leakage': 0.348086,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.167299,
           'Runtime Dynamic': 2097.98,
           'Subthreshold Leakage': 59.8706,
           'Subthreshold Leakage with power gating': 23.6631}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.4305015516636084,
          'Runtime Dynamic': 0.4305015516636084,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0421484,
         'Runtime Dynamic': 0.0353854,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 1160.28,
               'Gate Leakage': 4.89634,
               'Peak Dynamic': 48022.4,
               'Peak Power': 48094.2,
               'Runtime Dynamic': 2098.01,
               'Subthreshold Leakage': 66.8509,
               'Subthreshold Leakage with power gating': 27.6258,
               'Total Cores/Area': 1091.95,
               'Total Cores/Gate Leakage': 4.83071,
               'Total Cores/Peak Dynamic': 48022.4,
               'Total Cores/Runtime Dynamic': 2097.98,
               'Total Cores/Subthreshold Leakage': 59.8706,
               'Total Cores/Subthreshold Leakage with power gating': 23.6631,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.0421484,
               'Total L3s/Runtime Dynamic': 0.0353854,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 71.7473,
               'Total NoCs/Area': 6.41499,
               'Total NoCs/Gate Leakage': 0.0172096,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.17946,
               'Total NoCs/Subthreshold Leakage with power gating': 0.0672975}}