llvm :
	c++ -o out llvm-test.cpp -std=c++11 -g  -L/usr/lib/llvm-3.8/lib -L/usr/lib/llvm-c-3.8/lib`llvm-config --libs core jit native`   `llvm-config --cxxflags` `llvm-config --ldflags`
# `llvm-config --cxxflags --ldflags --libs core jit native` 
