power = {'BUSES': {'Area': 8.7167,
           'Bus/Area': 8.7167,
           'Bus/Gate Leakage': 0.0233844,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.243851,
           'Bus/Subthreshold Leakage with power gating': 0.091444,
           'Gate Leakage': 0.0233844,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.243851,
           'Subthreshold Leakage with power gating': 0.091444},
 'Core': [{'Area': 2068.52,
           'Execution Unit/Area': 1994.18,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0681896,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.256248,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.4799,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.515148,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 8.59497,
           'Execution Unit/Instruction Scheduler/Area': 1956.28,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.344008,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00151512,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 1.76857,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.658014,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0203725,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0110394,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 8.18141,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 65.9732,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.340924,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 132.987,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 6.6032,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 5.16833,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 2.94537,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 75241.9,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1889.96,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 7.83898,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 75107.1,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 3107.48,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 91.1344,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 34.2353,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 3114.74,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 96.3231,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 37.1917,
           'Execution Unit/Integer ALUs/Area': 3.76696,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.212233,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.388651,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.466896,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 3.21776,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 1.20666,
           'Execution Unit/Peak Dynamic': 75252.2,
           'Execution Unit/Register Files/Area': 28.3565,
           'Execution Unit/Register Files/Floating Point RF/Area': 9.63068,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.00825445,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 4.37312,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.105614,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.128663,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.0497709,
           'Execution Unit/Register Files/Gate Leakage': 0.026159,
           'Execution Unit/Register Files/Integer RF/Area': 18.7258,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0179046,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 2.92666,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.879335,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.273097,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.103541,
           'Execution Unit/Register Files/Peak Dynamic': 7.29978,
           'Execution Unit/Register Files/Runtime Dynamic': 0.984949,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.40176,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.153311,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.531766,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0698411,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 2.03723,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 12.9838,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 1.05889,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.397085,
           'Execution Unit/Runtime Dynamic': 3129.95,
           'Execution Unit/Subthreshold Leakage': 102.357,
           'Execution Unit/Subthreshold Leakage with power gating': 39.457,
           'Gate Leakage': 9.23713,
           'Instruction Fetch Unit/Area': 21.8028,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00282961,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00282961,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00248229,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000970623,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00186094,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0100024,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0264972,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.116748,
           'Instruction Fetch Unit/Instruction Buffer/Area': 2.64509,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.0346434,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 497.007,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 12.7498,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.290984,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.110014,
           'Instruction Fetch Unit/Instruction Cache/Area': 3.14635,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.029931,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.43323,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.333399,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.367022,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.180386,
           'Instruction Fetch Unit/Instruction Decoder/Area': 14.8639,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 10.9923,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.422981,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 517.199,
           'Instruction Fetch Unit/Runtime Dynamic': 13.5427,
           'Instruction Fetch Unit/Subthreshold Leakage': 1.36137,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.5701,
           'L2/Area': 4.53318,
           'L2/Gate Leakage': 0.015464,
           'L2/Peak Dynamic': 0.0517836,
           'L2/Runtime Dynamic': 0.0133647,
           'L2/Subthreshold Leakage': 0.834142,
           'L2/Subthreshold Leakage with power gating': 0.401066,
           'Load Store Unit/Area': 9.12408,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.2678,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.48909,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0582639,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0980497,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0980498,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.60547,
           'Load Store Unit/Runtime Dynamic': 2.07069,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.241774,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.483548,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.730943,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.335652,
           'Memory Management Unit/Area': 0.74897,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0858064,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0865749,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.0312611,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.399995,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0546829,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 2.24923,
           'Memory Management Unit/Runtime Dynamic': 0.141258,
           'Memory Management Unit/Subthreshold Leakage': 0.216232,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.0921915,
           'Peak Dynamic': 82947.9,
           'Renaming Unit/Area': 33.7259,
           'Renaming Unit/FP Front End RAT/Area': 0.284555,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00465468,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 23.4847,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 2.22729,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0482834,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.0275216,
           'Renaming Unit/Free List/Area': 10.8732,
           'Renaming Unit/Free List/Gate Leakage': 0.00143146,
           'Renaming Unit/Free List/Peak Dynamic': 8.54997,
           'Renaming Unit/Free List/Runtime Dynamic': 0.759361,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0369978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.0206997,
           'Renaming Unit/Gate Leakage': 0.296574,
           'Renaming Unit/Int Front End RAT/Area': 22.2087,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.264049,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 7136.03,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 259.384,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 3.48901,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 1.98873,
           'Renaming Unit/Peak Dynamic': 7170.6,
           'Renaming Unit/Runtime Dynamic': 262.371,
           'Renaming Unit/Subthreshold Leakage': 3.73357,
           'Renaming Unit/Subthreshold Leakage with power gating': 2.09669,
           'Runtime Dynamic': 3408.09,
           'Subthreshold Leakage': 111.111,
           'Subthreshold Leakage with power gating': 43.6569}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.10187546851840551,
          'Runtime Dynamic': 0.10187546851840551,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.0461236,
         'Runtime Dynamic': 0.0302879,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 2139.14,
               'Gate Leakage': 9.30893,
               'Peak Dynamic': 82947.9,
               'Peak Power': 83075.4,
               'Runtime Dynamic': 3408.12,
               'Subthreshold Leakage': 118.156,
               'Subthreshold Leakage with power gating': 47.7154,
               'Total Cores/Area': 2068.52,
               'Total Cores/Gate Leakage': 9.23713,
               'Total Cores/Peak Dynamic': 82947.9,
               'Total Cores/Runtime Dynamic': 3408.09,
               'Total Cores/Subthreshold Leakage': 111.111,
               'Total Cores/Subthreshold Leakage with power gating': 43.6569,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.0461236,
               'Total L3s/Runtime Dynamic': 0.0302879,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 127.465,
               'Total NoCs/Area': 8.7167,
               'Total NoCs/Gate Leakage': 0.0233844,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.243851,
               'Total NoCs/Subthreshold Leakage with power gating': 0.091444}}